### ISSUE TITLE
Save and print failure information for proofs loaded from disk

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#413]
As identified in https://github.com/runtimeverification/kontrol/pull/410#issuecomment-1980055055, failure information for the proof is not being printed if a proof is being read from disk (instead of being run with `--reinit`). This makes the information we're printing for the proof as well as the JUnit XML report incomplete.

**Comment by lisandrasilva** [comment]
This was introduced by this [change](https://github.com/runtimeverification/pyk/pull/903/files#diff-6826b573c72541d2929eabc83e981f608fe232e7a549bf631665358a2b48541aL734) in this [PR](https://github.com/runtimeverification/pyk/pull/903) in `pyk`. A possible fix is to update the `proof.failure` info with `proof.failure_info()` whenever we are reading a proof from disk in `Kontrol`, but I am wondering if this should be fixed in `pyk`. @nwatson22, what is your opinion?

**Comment by nwatson22** [comment]
The issue was with the `advance_proof` loop not setting the failure info when the loop executes 0 times. We still don't have failure info when simply loading a proof, but as long as `advance_proof` gets called on it the failure info should be recalculated with my linked PR.

**Comment by palinatolmach** [comment]
@nwatson22  @ehildenb the original issue with failure info not being assigned in XML report or when a proof is read with `kontrol prove` has been addressed. Shall we close this issue, or do you have anything else in mind for it?

**Comment by yale-vinson** [comment]
@palinatolmach Depending on their answer, we can close it or move it to Backlog. I think we are good enough for what we delivered to OPT for now, unless they complain about the XML we provided.

**Comment by palinatolmach** [comment]
The report-related part has been fixed, and, to my knowledge, there were no issues caused by the absence of failure upon proof loading. I'll close this issue, but can reopen it if we identify that it's needed.
